version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: LTS-Dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lts_core
    ports:
      - "3306:3306"
    volumes:
      - ./Data/Init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
