version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: LTS-Dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lts_core
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - ./Src/Data/Init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '127.0.0.1:6379:6379'
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  mysql-data:
