name: Bug Report
description: 버그를 발견했을 때 작성하는 템플릿
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: 버그 설명
      description: 어떤 문제가 발생했는지 명확히 적어주세요.
      placeholder: 예: 로그인 시 화면이 멈춤
  - type: textarea
    attributes:
      label: 재현 절차
      description: 문제가 발생한 절차를 단계별로 적어주세요.
      placeholder: |
        1. 로그인 버튼 클릭
        2. 아이디 입력
        3. 오류 발생
  - type: input
    attributes:
      label: 브라우저/환경
      placeholder: 예: Chrome 125 / Windows 11
