name: Test Coverage

on:
  pull_request:
    branches: [ "Dev" ]
  push:
    branches: [ "Dev" ]

jobs:
  build:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x" 

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Tests and collect coverage
        run: dotnet test LTS.Tests/LTS.Tests.csproj --collect:"XPlat Code Coverage"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./LTS.Tests/TestResults/**/*.cobertura.xml
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true
